## Install Java
- name: Install Jenkins dependencies
  ansible.builtin.dnf:
    name:
      - fontconfig
      - java-21-openjdk
    state: present
  

- name: Download Jenkins repository
  ansible.builtin.get_url:
    url: https://pkg.jenkins.io/rpm/jenkins.repo
    dest: /etc/yum.repos.d/jenkins.repo
    mode: '0644'

- name: Upgrade packages
  ansible.builtin.dnf:
    name: "*"
    state: latest

- name: Install Jenkins
  ansible.builtin.dnf:
    name: jenkins
    state: present

- name: Enable Jenkins
  ansible.builtin.systemd:
    name: jenkins
    enabled: true

- name: Start Jenkins
  ansible.builtin.systemd:
    name: jenkins
    state: started

- name: Add jenkins user to docker group
  ansible.builtin.user:
    name: jenkins
    groups: docker
    append: yes

- name: Restart Jenkins service to apply group changes
  ansible.builtin.systemd:
    name: jenkins
    state: restarted