---
- name: Configure Jenkins Server
  ansible.builtin.import_tasks: packages.yml

- name: Install Docker
  ansible.builtin.import_tasks: docker.yml

- name: Install Jenkins
  ansible.builtin.import_tasks: jenkins.yml

- name: Install kubectl
  ansible.builtin.import_tasks: kubectl.yml

- name: Install Ansible
  ansible.builtin.import_tasks: ansible.yml