## Install Docker And Start it 
- name: Install Docker
  ansible.builtin.dnf:
    name: docker
    state: present

- name: Enable Docker
  ansible.builtin.systemd:
    name: docker
    enabled: true

- name: Start Docker
  ansible.builtin.systemd:
    name: docker
    state: started

- name: Add ec2-user to docker group
  ansible.builtin.user:
    name: ec2-user
    groups: docker
    append: true
