---
## Update Packages
- name: Update Packages
  ansible.builtin.dnf:
    name: "*"
    state: latest
    update_cache: yes

- name: Set TimeZone
  community.general.timezone:
    name: "{{ timezone }}"

- name: Set Hostname
  ansible.builtin.hostname:
    name: "{{ hostname }}"

## Install some Packages
- name: Install required packages
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: latest
  loop: "{{ dependency_packages }}"



