[k8s_master]
100.31.134.170 ansible_user=ec2-user
[k8s_workers]
100.31.134.170 ansible_user=ec2-user
100.31.134.170 ansible_user=ec2-user

[jenkins]
13.218.92.146 ansible_user=ec2-user


[k8s:children]
k8s_master
k8s_workers