---

- name: Configure Web EC2
  ansible.builtin.import_tasks: packages.yml

- name: Install Docker
  ansible.builtin.import_tasks: docker.yml

- name: Install Kubernetes
  ansible.builtin.import_tasks: kubernetes.yml